/**
 * This application collects the following data from users:
 * 1) Date of journal entry
 * 2) Concepts covered (will be the title of the entry)
 * 3) Long-form contents of teh journal entry
 * 4) The mood of the journal entry
 * 
 *      This program:
 *      Holds the raw data about each entry and exports
 *      functions that other modules can use to filter
 *      the entries for different purposes.
 */

// This is the original data.
const journal = [
    {
        id: 1,
        date: "07/24/2025",
        concept: "HTML & CSS",
        entry: "We talked about HTML components and how to make grid layouts with Flexbox in CSS.",
        mood: "Ok"
    },
    {
        id: 2,
        date: "07/26/2025",
        concept: "Flexbox",
        entry: "CSS styling is kind of frustrating- I'm having a hard time getting flexbox to display my webpage the way I want it to.",
        mood: "Frustrated"
    },
    {
        id: 3,
        date: "07/29/2025",
        concept: "JavaScript",
        entry: "I'm really getting the hang of how to implement JavaScript in a web application! one of my projects is pretty close to having all its visual elements generated by JavaScript.",
        mood: "Optimistic"
    }
]

/*
    You export a function that provides a version of the
    raw data in the format that you want
*/
export const useJournalEntries = () => {
    const sortedByDate = journal.sort(
        (currentEntry, nextEntry) =>
            Date.parse(currentEntry.date) - Date.parse(nextEntry.date)
    )
    return sortedByDate
}